import { createTheme } from '@mantine/core';

export const theme = createTheme({
  colors: {
    deepBlue: [
      '#f0f4ff',
      '#e1ecff',
      '#c3d6ff',
      '#a1bfff', 
      '#7ea7ff',
      '#5b8fff',
      '#3b7fff',
      '#2563eb',
      '#1d4ed8',
      '#1e3a8a',
    ],
    softOrange: [
      '#fff7ed',
      '#ffedd5',
      '#fed7aa',
      '#fdba74',
      '#fb923c',
      '#f97316',
      '#ea580c',
      '#dc2626',
      '#b91c1c',
      '#991b1b',
    ],
    gray: [
      '#f9fafb',
      '#f3f4f6',
      '#e5e7eb',
      '#d1d5db',
      '#9ca3af',
      '#6b7280',
      '#4b5563',
      '#374151',
      '#1f2937',
      '#111827',
    ],
  },
  primaryColor: 'deepBlue',
  defaultRadius: 'md',
  fontFamily: 'var(--font-nunito-sans), Nunito Sans, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  headings: {
    fontFamily: 'var(--font-nunito), Nunito, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    fontWeight: '700',
  },
  fontSizes: {
    xs: '0.75rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
    '6xl': '3.75rem',
  },
}); 